defaults: &defaults
  business_email: tapgyn@gmail.com

development:
  <<: *defaults
  domain: 0.0.0.0:3000

test:
  <<: *defaults
  domain: test.host

production:
  <<: *defaults
  domain: example.com
